# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    flysystem_local:
        class: League\Flysystem\Adapter\Local
        public: false
        arguments:
          - "%uploads_dir%"



    flysystem:
        class: League\Flysystem\Filesystem
        arguments:
          - "@flysystem_local"